name: Notify Discord on PR

on:
  pull_request:
    types: [opened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - name: Validate DISCORD_WEBHOOK_URL secret
        shell: bash
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          if [ -z "$DISCORD_WEBHOOK_URL" ]; then
            echo "❌ ERROR: DISCORD_WEBHOOK_URL is not set. Aborting workflow to avoid unnecessary execution."
            exit 1
          fi
          echo "✅ DISCORD_WEBHOOK_URL is properly set. Proceeding with the workflow."

      - name: Send Discord notification with embed
        run: |
          EMBED_PAYLOAD=$(cat <<EOF
          {
            "embeds": [{
              "title": "${{ github.event.pull_request.title }}",
              "url": "${{ github.event.pull_request.html_url }}",
              "description": "새 Pull Request가 생성되었습니다.",
              "color": 5814783,
              "author": {
                "name": "${{ github.event.pull_request.user.login }}"
              },
              "fields": [
                {
                  "name": "리포지토리",
                  "value": "${{ github.repository }}",
                  "inline": true
                },
                {
                  "name": "작성자",
                  "value": "${{ github.event.pull_request.user.login }}",
                  "inline": true
                }
              ],
              "timestamp": "${{ github.event.pull_request.created_at }}"
            }]
          }
          EOF
          )

          curl -X POST \
               -H "Content-Type: application/json" \
               -d "$EMBED_PAYLOAD" \
               "$DISCORD_WEBHOOK_URL"
